export const GOLONGAN_EMOJI: Record<string, string> = {
  "Hati Es Batu": "🧊",
  "Santuy Society": "😌",
  "Kepo Tapi Jaim": "🫣",
  "Centang Biru Hunter": "⚡",
  "Mode Siaga HP": "🔔",
  "Senyum Sendiri Gang": "😄",
  "Stalker Bersertifikat": "👁️",
  "Chat Lama = Playlist Favorit": "📱",
  "Butuh Centang Biru Detik Ini": "🔵",
  "Tim Overthinking Sejagat": "🌀",
  "Cancel Semua Demi Doi": "📅",
  "Panic Online Tapi Hening": "😰",
  "Sutradara Masa Depan": "🎬",
  "Doi Gak Pernah Salah": "🛡️",
  "Bunglon Demi Doi": "🦎",
  "Detektif Circle Doi": "🔍",
  "All In Tanpa Rem": "🚀",
  "Bahaya Tau Tapi Gas Aja": "⚠️",
  "Withdrawal Doi Sehari Aja": "💔",
  "Bucin Akut Tingkat Dewa": "👑",
};
